INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('forza-6', 'Forza Horizon 6', 'CORRIDA - MUNDO ABERTO', true, 'A sua Aventura Horizon definitiva esta a sua espera. Explore as vibrantes e paisagens de mundo aberto com corridas divertidas e sem limites enquanto pilota centenas dos melhores carros do mundo. Participe de eventos climaticos impressionantes e sinta a adrenalina da velocidade em pistas incriveis.', '15.90', '199.20', 'https://raw.githubusercontent.com/YuriDavid1/Game-Library-Manager---Assets/refs/heads/master/forza/carrossel2.webp', 'https://raw.githubusercontent.com/YuriDavid1/Game-Library-Manager---Assets/refs/heads/master/forza/capa.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('cyberpunk', 'Cyberpunk 2077', 'RPG - FICCAO CIENTIFICA', true, 'Cyberpunk 2077 e um RPG de acao e aventura em mundo aberto que se passa em Night City, uma megalopole obcecada por poder, glamour e modificacoes corporais. Jogue como V, um mercenario fora da lei, e explore uma cidade onde as suas escolhas moldam a historia e o mundo ao seu redor. Personalize seu personagem e lute pela sobrevivencia.', '19.90', '159.90', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('elden-ring', 'Elden Ring', 'RPG - ACAO', false, 'Levante-se, Maculado, e seja guiado pela graca para portar o poder do Anel Pristino e se tornar um Lorde Pristino nas Terras Intermedias. Um vasto mundo perfeitamente conectado espera por voce. Explore labirintos complexos, enfrente chefes colossais e desvende os segredos sombrios criados por Hidetaka Miyazaki e George R. R. Martin.', '24.90', '183.90', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('rdr2', 'Red Dead Redemption 2', 'MUNDO ABERTO - ACAO', true, 'Estados Unidos, 1899. Arthur Morgan e a gangue Van der Linde sao forcados a fugir. Com agentes federais e os melhores cacadores de recompensas no seu encalco, a gangue precisa roubar e lutar para sobreviver no implacavel coracao dos Estados Unidos. Viva uma jornada epica sobre honra e lealdade.', '24.90', '191.90', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1174180/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1174180/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('god-of-war', 'God of War', 'ACAO - AVENTURA', true, 'Com a vinganca contra os deuses do Olimpo no passado, Kratos agora vive no reino das divindades e monstros nordicos. E nesse mundo duro e implacavel que ele deve lutar para sobreviver e ensinar seu filho a fazer o mesmo. Uma jornada brutal e emocionante que redefine os limites do combate corpo a corpo.', '18.90', '159.90', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1593500/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1593500/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('witcher-3', 'The Witcher 3: Wild Hunt', 'RPG - FANTASIA', true, 'Voce e Geralt de Rivia, um mercenario matador de monstros. O continente devastado pela guerra e infestado de criaturas e o seu campo de exploracao. Seu contrato atual? Encontrar Ciri, a Crianca da Profecia, uma arma viva capaz de alterar a forma do mundo. Domine magias, crie pocoes e tome decisoes com pesos reais.', '15.90', '103.90', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/292030/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/292030/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('gta-v', 'Grand Theft Auto V', 'ACAO - MUNDO ABERTO', true, 'Quando um malandro de rua, um ladrao de bancos aposentado e um psicopata aterrorizante se envolvem com os criminosos mais assustadores do submundo e do governo, eles precisam realizar uma serie de golpes ousados para sobreviver em uma cidade implacavel onde nao podem confiar em ninguem, nem mesmo uns nos outros.', '12.90', '66.90', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/271590/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/271590/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('baldurs-gate', 'Baldurs Gate 3', 'RPG - ESTRATEGIA', true, 'Reuna seu grupo e retorne a Forgotten Realms em uma historia de amizade e traicao, sacrificio e sobrevivencia, e a atracao pelo poder absoluto. Habilidades misteriosas estao despertando dentro de voce. Resista e volte a escuridao contra si mesma ou abrace a corrupcao. Escolha entre diversas racas e classes e molde seu destino.', '25.90', '159.90', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1086940/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1086940/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('re4', 'Resident Evil 4', 'TERROR - ACAO', true, 'Sobreviver e apenas o comeco. Seis anos se passaram desde o desastre biologico em Raccoon City. O agente Leon S. Kennedy e enviado para resgatar a filha sequestrada do presidente em uma vila europeia isolada. Enfrente horrores inimaginaveis e descubra o que se esconde nas sombras desta comunidade enlouquecida.', '20.90', '169.00', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2050650/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2050650/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('hollow-knight', 'Hollow Knight', 'METROIDVANIA - PLATAFORMA', true, 'Forje seu proprio caminho em Hollow Knight. Uma aventura epica de acao atraves de um vasto reino arruinado de insetos e herois. Explore cavernas sinuosas, lute contra criaturas corrompidas e faca amizade com insetos bizarros em um estilo de arte 2D incrivelmente desenhado a mao.', '9.90', '46.99', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/367520/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/367520/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('horizon-zero-dawn', 'Horizon Zero Dawn', 'MUNDO ABERTO - RPG', true, 'Viva a emocionante jornada de Aloy para descobrir os misterios de uma Terra futura controlada por Maquinas mortais. Exilada da sua tribo, ela embarca em uma aventura pelo mundo para desvendar seu passado e impedir uma ameaca letal que quer destruir o que restou da humanidade.', '14.90', '199.90', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1151640/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1151640/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('spider-man', 'Spider-Man Remastered', 'ACAO - SUPER-HEROI', true, 'Em Marvels Spider-Man Remasterizado, os mundos de Peter Parker e do Homem-Aranha entram em conflito em uma historia original repleta de acao. Jogue como um Peter experiente combatendo grandes crimes e viloes iconicos nas ruas detalhadas de Nova York, balancando pelas teias a qualquer momento.', '22.90', '249.90', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1817070/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1817070/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('stardew-valley', 'Stardew Valley', 'SIMULACAO - CASUAL', true, 'Voce herdou o antigo lote de fazenda do seu avo em Stardew Valley. Equipado com ferramentas de segunda mao e algumas moedas, voce parte para comecar sua nova vida no campo. Aprenda a viver da terra e transforme esses campos cobertos de mato em um lar prospero e cheio de vida.', '5.90', '24.99', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/413150/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/413150/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('palworld', 'Palworld', 'SOBREVIVENCIA - CRAFTING', true, 'Colecione criaturas fantasticas chamadas Pals neste vasto mundo aberto focado em sobrevivencia e construcao. Coloque-os para batalhar em combates armados, construir suas bases, cultivar suas fazendas ou ate mesmo trabalhar em fabricas automatizadas enquanto explora um mundo selvagem e sem limites.', '16.90', '88.00', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1623730/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1623730/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('ghost-of-tsushima', 'Ghost of Tsushima', 'ACAO - SAMURAI', true, 'No final do seculo XIII, o imperio mongol devastou nacoes inteiras ao longo de sua campanha para conquistar o Oriente. O guerreiro samurai Jin Sakai precisa proteger o que restou de seu povo e recuperar seu lar a todo custo, abandonando as tradicoes honradas para se tornar o temido Fantasma.', '24.90', '249.00', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2215430/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2215430/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('hogwarts', 'Hogwarts Legacy', 'RPG - MUNDO ABERTO', true, 'Hogwarts Legacy e um RPG de acao e mundo aberto ambientado no universo apresentado nos livros de Harry Potter. Explore o castelo, descubra feras magicas, personalize seu personagem, prepare pocoes, aprenda feiticos masterizados e decida o destino do mundo bruxo com as suas escolhas.', '22.90', '249.90', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/990080/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/990080/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('doom-eternal', 'DOOM Eternal', 'TIRO - FPS', true, 'Os exercitos do inferno invadiram a Terra. Torne-se o implacavel Slayer em uma campanha epica para um jogador e conquiste demonios entre dimensoes. Interrompa a destruicao final da humanidade com um arsenal pesado, movimentacao fluida e o puro extase do combate agil e sangrento.', '14.90', '149.00', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/782330/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/782330/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('sekiro', 'Sekiro: Shadows Die Twice', 'ACAO - DIFICIL', true, 'Explore o Japao do final do periodo Sengoku no final do seculo XVI. Voce e o lobo de um braco so, um guerreiro desfigurado e exilado resgatado da beira da morte encarregado de proteger um jovem lorde. Domine a arte do combate de espadas preciso e nao hesite diante da morte iminente.', '19.90', '199.00', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/814380/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/814380/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('hades', 'Hades', 'ROGUE-LIKE - INDIE', true, 'Desafie o deus dos mortos enquanto voce batalha para sair do Submundo da mitologia grega neste jogo de simulacao de masmorras estilo rogue-like. Cada tentativa de fuga revela mais sobre a historia rica e melhora suas habilidades e armas abencoadas pelos deuses do Olimpo.', '11.90', '73.99', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145360/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145360/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('dead-cells', 'Dead Cells', 'ROGUE-LIKE - PLATAFORMA', true, 'Dead Cells e um jogo de plataforma de acao estilo rogue-lite e metroidvania. Explore um castelo gigante em constante mutacao e expansao, assumindo combates brutais e velozes em 2D contra chefes implacaveis. Nao ha checkpoints. Mate, morra, aprenda, repita.', '11.90', '47.50', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/588650/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/588650/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('terraria', 'Terraria', 'SANDBOX - AVENTURA', true, 'Cave, lute, explore e construa. Nada e impossivel neste jogo de aventura cheio de acao focado na criatividade e sobrevivencia. O mundo e sua tela e a propria terra e o seu material de construcao. Prepare-se para enfrentar chefes poderosos no subterraneo.', '4.90', '19.99', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/105600/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/105600/library_600x900_2x.jpg');

INSERT INTO jogo (slug, nome, genero, disponivel, descricao, preco_aluguel, preco_compra, imagem_fundo, imagem_capa) VALUES ('garrys-mod', 'Garrys Mod', 'SANDBOX - FISICA', true, 'Garrys Mod e uma caixa de areia fisica sem regras. Nao ha objetivos predefinidos. Nos damos as ferramentas e deixamos voce jogar livremente, criando maquinas, mecanismos complexos e ate mesmo modos de jogo inteiramente novos junto com a comunidade.', '7.90', '34.99', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/4000/page_bg_generated_v6b.jpg', 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/4000/library_600x900_2x.jpg');