name: Deploy - Produção

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: |
          cd game-library
          chmod +x mvnw
          ./mvnw -B clean package -DskipTests

      - name: Message
        run: echo "Build OK "